# Generated by Django 2.0.6 on 2019-07-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emplist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=7)),
                ('age', models.SmallIntegerField()),
                ('headpic', models.ImageField(upload_to='pics')),
            ],
            options={
                'db_table': 'emplist',
            },
        ),
    ]
